#!/bin/bash

TARGET_NOVERSION=libpotados.so
TARGET=$TARGET_NOVERSION.1.0.0

make clean
rm -f /usr/local/lib/libpotados.so*

make
cp $TARGET /usr/local/lib
ln -s /usr/local/lib/$TARGET /usr/local/lib/$TARGET_NOVERSION
